/* eslint-disable prettier/prettier */
// const TIMER_DEFAULT_STUDYING_TIME_IN_SECONDS = 60 * 25;
// const TIMER_DEFAULT_PAUSE_TIME_IN_SECONDS = 60 * 5;
// const TIMER_DEFAULT_BREAK_TIME_IN_SECONDS = 60 * 15;
const TIMER_DEFAULT_STUDYING_TIME_IN_SECONDS = 10;
const TIMER_DEFAULT_PAUSE_TIME_IN_SECONDS = 5;
const TIMER_DEFAULT_BREAK_TIME_IN_SECONDS = 15;

export const MAX_STUDYING_TIMES_BEFORE_SWITCHING = 2;

export enum POMODORO_MODE {
  Studying,
  Pause,
  Break,
}

export enum EVENTS {
  FINISHED_TIMER,
}

export const TIMER_DEFAULT_TIME = {
  [POMODORO_MODE.Studying]: TIMER_DEFAULT_STUDYING_TIME_IN_SECONDS,
  [POMODORO_MODE.Pause]: TIMER_DEFAULT_PAUSE_TIME_IN_SECONDS,
  [POMODORO_MODE.Break]: TIMER_DEFAULT_BREAK_TIME_IN_SECONDS,
};
